add some type annotations to adafruit_minimqtt.py
adafruit/Adafruit_CircuitPython_MiniMQTT pull request #158
Opened 2023-02-25 09:21 UTC by vladak

This change adds more type annotations. `mypy --strict adafruit_minimqtt/adafruit_minimqtt.py` currently reports 99 errors (down from 168).

Approaches #92.

2023-02-27 20:45 UTC, FoamyGuy requested changes
Thank you for working on this @vladak! as well as all of the other improvements you've been making to this library. 

I had a look over this and found a few things that I think we will want to change. 

I'm also going to try it out on a device, I'll report back here with the results. Ordinarily types shouldn't change functionality at all, but there are a few cases I want to double check.

2023-02-27 20:45 UTC, FoamyGuy commented on adafruit_minimqtt/adafruit_minimqtt.py
>          string with the exact number of bytes requested.
Can we update this docstring be to:

```
"Will only return bytearray with the exact number..."
```
It references string currently but looks to return a bytearray from the code and typing annotation added.

2023-02-27 20:56 UTC, FoamyGuy commented on adafruit_minimqtt/adafruit_minimqtt.py
> +        self._timestamp: float = 0
I did test this successfully with an mpy build of the branch from this PR all appears to be working as intended

2023-02-28 19:46 UTC, vladak commented on adafruit_minimqtt/adafruit_minimqtt.py
> +        self._timestamp: float = 0
Cool. I was a bit surprised myself to discover these.

2023-02-28 19:53 UTC, vladak commented on adafruit_minimqtt/adafruit_minimqtt.py
> +        port: Union[int, None] = None,
Ack. I hope I got all of them.

2023-02-28 19:55 UTC, vladak commented on adafruit_minimqtt/adafruit_minimqtt.py
> +        payload: Union[int, float, str, None] = None,
Makes sense.

2023-02-28 20:07 UTC, vladak commented on adafruit_minimqtt/adafruit_minimqtt.py
> +    def __exit__(self, exception_type, exception_value, traceback) -> None:
Found the type hints on [SO](https://stackoverflow.com/questions/58808055/what-are-the-python-builtin-exit-argument-types). It's not clear to me whether it should return `bool` as suggested.

2023-02-28 20:09 UTC, vladak commented on adafruit_minimqtt/adafruit_minimqtt.py
> +    def add_topic_callback(self, mqtt_topic: str, callback_method) -> None:
Yeah, I avoid `Callable` because it usually opens an avenue to whole bunch of type hints to be added. Will look into it.

2023-03-01 17:26 UTC, vladak commented on adafruit_minimqtt/adafruit_minimqtt.py
> +    def add_topic_callback(self, mqtt_topic: str, callback_method) -> None:
I'd rather leave these callbables till the next PR.

2023-03-01 17:27 UTC, vladak commented
For now, I am done with the changes, unless more issues are found. Will save the more complicated stuff (Callables in particular) till next time.

2023-03-06 16:20 UTC, FoamyGuy approved these changes
Looks good to me. 

Thank you @vladak

2023-03-06 16:20 UTC, merged