timout 1 instead of 0
adafruit/Adafruit_CircuitPython_MiniMQTT pull request #228
Opened 2024-11-22 19:18 UTC by FoamyGuy

@ladyada 
Resolves: #227 

Solution discussed with @brentru on discord. I did try changing the cpython examples to use 0, but that still leads to the exception being raised about being shorter than the socket timeout, so I've left them alone in this PR.

2024-11-22 19:26 UTC, dhalbert requested changes
Suggestion:
The current code is:
```py
        if timeout < self._socket_timeout:
            raise MMQTTException(
                f"loop timeout ({timeout}) must be bigger "
                + f"than socket timeout ({self._socket_timeout}))"
            )
```
The test is actually <, not <=, so a more precise message would be `... must be >=  ...` instead of `... must be bigger ...`.

Now, in terms of actually working properly, should the loop timeout be absolutely greater than the socket timeout, or just greater or equal?

query for @brentru

2024-11-22 19:30 UTC, brentru commented
>  should the loop timeout be absolutely greater than the socket timeout, or just greater or equal?

Greater or equal

2024-11-25 14:59 UTC, FoamyGuy commented
Thank you @dhalbert and @brentru, the message is updated with the latest commit to `>=` instead of `bigger`

2024-11-25 15:01 UTC, brentru approved these changes

2024-11-25 15:07 UTC, dhalbert requested changes

2024-11-25 15:07 UTC, dhalbert commented on adafruit_minimqtt/adafruit_minimqtt.py
>                  + f"than socket timeout ({self._socket_timeout}))"
grammar fix
```suggestion
                + f"socket timeout ({self._socket_timeout}))"
```

2024-11-25 15:08 UTC, dhalbert approved these changes

2024-11-25 15:15 UTC, merged